CC = gcc
CFLAGS = -std=gnu99 -pedantic -Wall -O3

# TODO: add a rule that compiles test.c into a program called "test".
# The grader runs `make` in this directory and then runs ./test .
test: test.c
	@echo "TODO: no rule yet to compile test.c into ./test" >&2
	@exit 1
