/**
 * Putting `grade` on the PATH.
 *
 * `bun link` is not enough: it registers the package but creates no global
 * binary, and `~/.bun/bin` is frequently absent from PATH. So `grade install`
 * writes a small shim itself and tells the truth about whether that location is
 * actually reachable.
 *
 * The search order deliberately avoids directories owned by other version
 * managers (pyenv, nvm, pnpm shims): dropping a file there works until that
 * tool rewrites its shim directory, and then the command silently vanishes.
 */

import { chmod, mkdir, rm, writeFile } from "node:fs/promises";
import { existsSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { packageRoot } from "./paths.ts";

export interface InstallLocation {
  dir: string;
  onPath: boolean;
  /** True when the directory exists but is not in PATH, so a line must be added. */
  needsPathEntry: boolean;
}

/** Directories that belong to another tool and should not be written to. */
const MANAGED_BY_OTHERS = [
  ".nvm/",
  ".pyenv/",
  ".rbenv/",
  ".nodenv/",
  "pnpm/bin",
  "JetBrains/Toolbox",
  "Cargo/bin",
  "go/bin",
];

function pathDirs(): string[] {
  return (process.env.PATH ?? "").split(path.delimiter).filter(Boolean);
}

/**
 * Pick where to install. Prefers a directory already on PATH, in this order:
 * `~/.local/bin`, Homebrew, `/usr/local/bin`, then any other writable PATH
 * directory that another tool does not manage.
 */
export function chooseInstallDir(explicit?: string): InstallLocation {
  if (explicit) {
    const dir = path.resolve(explicit);
    return {
      dir,
      onPath: pathDirs().includes(dir),
      needsPathEntry: !pathDirs().includes(dir),
    };
  }

  const home = process.env.HOME ?? "";
  const dirs = pathDirs();

  const candidates: string[] = [
    path.join(home, ".local", "bin"),
    "/opt/homebrew/bin",
    "/usr/local/bin",
  ];
  for (const d of dirs) {
    if (!candidates.includes(d)) candidates.push(d);
  }

  for (const dir of candidates) {
    if (!dir || !path.isAbsolute(dir)) continue;
    if (MANAGED_BY_OTHERS.some((m) => dir.includes(m))) continue;
    const onPath = dirs.includes(dir);
    if (!onPath) continue; // an off-PATH directory saves the user nothing
    if (existsSync(dir) && !isWritable(dir)) continue;
    return { dir, onPath: true, needsPathEntry: false };
  }

  // Nothing usable on PATH: fall back and tell the user what to add.
  const fallback = path.join(home, ".local", "bin");
  return { dir: fallback, onPath: false, needsPathEntry: true };
}

/** Actually try to create a file, rather than trusting permission bits. */
function isWritable(dir: string): boolean {
  const probe = path.join(dir, `.grade-write-test-${process.pid}`);
  try {
    writeFileSync(probe, "");
    rmSync(probe, { force: true });
    return true;
  } catch {
    return false;
  }
}

/** The shim's contents: run the package entry point with the caller's args. */
function shimBody(root: string): string {
  const bun = Bun.which("bun") ?? "bun";
  return `#!/bin/sh
# Generated by \`grade install\`. Runs the grader from the package checkout.
# If you move the package, re-run \`grade install\` from its new location, or
# set GRADE_PACKAGE.
exec ${JSON.stringify(bun)} ${JSON.stringify(path.join(root, "src", "index.ts"))} "$@"
`;
}

export interface InstallOutcome {
  location: InstallLocation;
  shim: string;
  installed: boolean;
  reason?: string;
}

export async function installCommand(explicitDir?: string): Promise<InstallOutcome> {
  const root = packageRoot();
  const location = chooseInstallDir(explicitDir);
  const shim = path.join(location.dir, "grade");

  if (existsSync(shim)) {
    const existing = await Bun.file(shim).text();
    // Only overwrite something this tool wrote. Refusing is safer than
    // clobbering an unrelated program that happens to be called `grade`.
    if (!existing.includes("Generated by `grade install`")) {
      return {
        location,
        shim,
        installed: false,
        reason: `${shim} already exists and was not created by grade install`,
      };
    }
  }

  await mkdir(location.dir, { recursive: true });
  await writeFile(shim, shimBody(root));
  await chmod(shim, 0o755);
  return { location, shim, installed: true };
}

export async function uninstallCommand(explicitDir?: string): Promise<{ shim: string; removed: boolean }> {
  const location = chooseInstallDir(explicitDir);
  const shim = path.join(location.dir, "grade");
  if (!existsSync(shim)) return { shim, removed: false };
  const existing = await Bun.file(shim).text();
  if (!existing.includes("Generated by `grade install`")) {
    return { shim, removed: false };
  }
  await rm(shim, { force: true });
  return { shim, removed: true };
}

/** Which shell rc file to suggest, based on $SHELL. */
export function shellRcFile(): string {
  const shell = process.env.SHELL ?? "";
  const home = process.env.HOME ?? "~";
  if (shell.endsWith("/zsh")) return path.join(home, ".zshrc");
  if (shell.endsWith("/bash")) return path.join(home, ".bashrc");
  if (shell.endsWith("/fish")) return path.join(home, ".config", "fish", "config.fish");
  return path.join(home, ".profile");
}

/** The line a user must add when the install directory is not on PATH. */
export function pathLineFor(dir: string): string {
  if ((process.env.SHELL ?? "").endsWith("/fish")) {
    return `fish_add_path ${dir}`;
  }
  return `export PATH="${dir}:$PATH"`;
}

export interface Diagnostic {
  label: string;
  ok: boolean;
  detail: string;
}

/** `grade doctor`: report everything that could stop the tool working. */
export async function diagnose(): Promise<Diagnostic[]> {
  const root = packageRoot();
  const out: Diagnostic[] = [];

  out.push({
    label: "package",
    ok: existsSync(path.join(root, "data", "configs")),
    detail: root,
  });

  const bun = Bun.which("bun");
  out.push({
    label: "bun",
    ok: bun !== null,
    detail: bun ?? "not found on PATH",
  });

  const cc = Bun.which(process.env.CC ?? "cc");
  out.push({
    label: "C compiler",
    ok: cc !== null,
    detail:
      cc ??
      "not found — most assignments compile C. macOS: xcode-select --install; " +
        "Windows: install gcc via MSYS2 and set CC=gcc (MSVC is not supported)",
  });

  // `grade` reachable by name?
  const onPath = Bun.which("grade");
  out.push({
    label: "grade on PATH",
    ok: onPath !== null,
    detail: onPath ?? "not installed — run: grade install",
  });

  if (process.platform === "darwin") {
    const leaks = Bun.which("leaks");
    out.push({
      label: "leak checker",
      ok: leaks !== null,
      detail: leaks ? `${leaks} (ASan + leaks)` : "missing; memory_check cannot detect leaks",
    });
  } else if (process.platform === "linux") {
    const vg = Bun.which("valgrind");
    out.push({
      label: "leak checker",
      ok: vg !== null,
      detail: vg ? `${vg} (the original course's engine)` : "valgrind missing; falling back to ASan only",
    });
  }

  out.push({
    label: "line endings",
    ok: existsSync(path.join(root, ".gitattributes")),
    detail: existsSync(path.join(root, ".gitattributes"))
      ? ".gitattributes present (no EOL conversion)"
      : "MISSING — a Windows checkout would convert fixtures to CRLF and break grading",
  });

  return out;
}
