/**
 * The student's workspace.
 *
 * A workspace is any directory outside the package. `init` creates one and
 * hands out the first assignment; `grade` works inside it and unlocks the next
 * one on a pass.
 *
 * Layout of a workspace:
 *
 *   <workspace>/
 *     package.json          so that `bun grade` works from any subdirectory
 *     grade                 a shell shim, so `./grade` works too
 *     .grade/state.json     progress: which assignment is current, which are done
 *     00_hello/             the assignment you are working on
 *     01_apple/             unlocked after 00_hello passes
 *     ...
 *
 * State lives here rather than in the package because the package is shared,
 * read-only, and open-sourced — two students cloning it must not share progress.
 */

import { cp, mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { ConfigError, compareAssignmentIds, listAssignmentIds, readConfig } from "./config.ts";
import { STATE_DIR, STATE_FILE, isInside, packageRoot, stateFile, templateFor } from "./paths.ts";

export const STATE_VERSION = 1;

export interface WorkspaceState {
  version: number;
  /** ISO timestamp of `init`. */
  initialized: string;
  /** The assignment the student is currently expected to be working on. */
  current: string | null;
  /** Assignments that have passed, oldest first. */
  completed: string[];
  /** Where the package was when the workspace was created. */
  packageRoot: string;
}

export class WorkspaceError extends Error {}

// ---------------------------------------------------------------------------
// state
// ---------------------------------------------------------------------------

export async function readState(workspace: string): Promise<WorkspaceState | null> {
  const file = stateFile(workspace);
  if (!existsSync(file)) return null;
  try {
    const parsed = (await Bun.file(file).json()) as WorkspaceState;
    if (typeof parsed?.current !== "string" && parsed?.current !== null) return null;
    return {
      version: parsed.version ?? STATE_VERSION,
      initialized: parsed.initialized ?? new Date().toISOString(),
      current: parsed.current ?? null,
      completed: Array.isArray(parsed.completed) ? parsed.completed : [],
      packageRoot: parsed.packageRoot ?? packageRoot(),
    };
  } catch {
    throw new WorkspaceError(`${path.join(STATE_DIR, STATE_FILE)} is not valid JSON`);
  }
}

export async function writeState(workspace: string, state: WorkspaceState): Promise<void> {
  await mkdir(path.join(workspace, STATE_DIR), { recursive: true });
  await writeFile(stateFile(workspace), JSON.stringify(state, null, 2) + "\n");
}

// ---------------------------------------------------------------------------
// init
// ---------------------------------------------------------------------------

export interface InitOptions {
  /** Directory to create the workspace in. Created if missing. */
  dir: string;
  /** Assignment to hand out first. Defaults to the lowest-sorted config. */
  startAt?: string;
  /** Re-create `package.json` / `grade` shim even if the workspace exists. */
  repair?: boolean;
}

export interface InitOutcome {
  workspace: string;
  assignment: string;
  files: string[];
}

/** The package.json a workspace needs for `bun grade` to resolve. */
function workspaceManifest(root: string): string {
  return (
    JSON.stringify(
      {
        name: "duke-homework",
        private: true,
        description: "Assignments for the Duke Programming Practice specialization",
        scripts: {
          // Absolute so `bun grade` works from any subdirectory. Re-run
          // `grade init --repair` if the package moves.
          // `bun <file>` rather than `bun run <file>`: the latter wraps the
          // call in a script runner that echoes the command and reports a
          // non-zero exit as "script exited with code 1", which is noise for
          // an ordinary FAILED grade.
          grade: `bun ${JSON.stringify(path.join(root, "src", "index.ts"))}`,
        },
      },
      null,
      2,
    ) + "\n"
  );
}

/** A shim so `./grade` works without going through Bun's script runner. */
function workspaceShim(root: string): string {
  return `#!/bin/sh
# Generated by \`grade init\`. Runs the grader from the package checkout.
exec bun ${JSON.stringify(path.join(root, "src", "index.ts"))} "$@"
`;
}

export async function initWorkspace(opts: InitOptions): Promise<InitOutcome> {
  const root = packageRoot();
  const workspace = path.resolve(opts.dir);

  if (isInside(workspace, root)) {
    throw new WorkspaceError(
      `refusing to create a workspace inside the package (${path.relative(root, workspace) || "."}).\n` +
        `The package is the read-only index; pick a directory outside it, e.g.\n` +
        `  grade init ~/duke-homework`,
    );
  }

  const ids = await listAssignmentIds(root);
  if (ids.length === 0) throw new WorkspaceError("the package contains no assignment configs");

  const startAt = opts.startAt ?? ids[0]!;
  if (!ids.includes(startAt)) {
    throw new WorkspaceError(
      `unknown assignment "${startAt}". Known ids: ${ids.join(", ")}`,
    );
  }

  await mkdir(workspace, { recursive: true });

  // Refuse to initialise on top of stray assignment directories. Without this
  // a leftover half-graded folder silently mixes with the new ones, which is
  // confusing precisely because it looks almost right.
  const stray = (await readdir(workspace, { withFileTypes: true }))
    .filter((e) => e.isDirectory() && ids.includes(e.name))
    .map((e) => e.name);
  if (stray.length > 0 && !opts.repair) {
    throw new WorkspaceError(
      `${workspace} already contains assignment director${stray.length === 1 ? "y" : "ies"}: ` +
        `${stray.join(", ")}\n` +
        `Refusing to mix a fresh start with existing work. Either pick an empty directory,\n` +
        `or delete those folders first if you meant to start over.`,
    );
  }

  const existing = await readState(workspace);
  if (existing && !opts.repair) {
    throw new WorkspaceError(
      `${workspace} is already a grade workspace (current: ${existing.current ?? "none"}).\n` +
        `Use --repair to rewrite the launcher files, or pick another directory.`,
    );
  }

  // Launcher files.
  await writeFile(path.join(workspace, "package.json"), workspaceManifest(root));
  const shim = path.join(workspace, "grade");
  await writeFile(shim, workspaceShim(root));
  await Bun.$`chmod +x ${shim}`.quiet().nothrow();

  // First assignment.
  const files = await scaffoldAssignment(root, workspace, startAt);

  const state: WorkspaceState = {
    version: STATE_VERSION,
    initialized: existing?.initialized ?? new Date().toISOString(),
    current: startAt,
    completed: existing?.completed ?? [],
    packageRoot: root,
  };
  await writeState(workspace, state);

  return { workspace, assignment: startAt, files };
}

// ---------------------------------------------------------------------------
// assignment directory creation
// ---------------------------------------------------------------------------

async function listFiles(dir: string, prefix = ""): Promise<string[]> {
  const out: string[] = [];
  for (const e of await readdir(path.join(dir, prefix), { withFileTypes: true })) {
    const rel = prefix ? path.join(prefix, e.name) : e.name;
    if (e.isDirectory()) out.push(...(await listFiles(dir, rel)));
    else if (e.isFile()) out.push(rel);
  }
  return out.sort();
}

/**
 * Copy `data/templates/<id>/` into the workspace as `<id>/`.
 * Never overwrites: a student's work is never silently replaced.
 */
export async function scaffoldAssignment(
  root: string,
  workspace: string,
  id: string,
  targetName = id,
): Promise<string[]> {
  const target = path.join(workspace, targetName);
  if (existsSync(target)) return [];

  const template = templateFor(root, id);
  if (!existsSync(template) || !(await stat(template)).isDirectory()) {
    throw new WorkspaceError(`the package has no template for "${id}" (expected data/templates/${id}/)`);
  }

  await mkdir(target, { recursive: true });
  await cp(template, target, { recursive: true });
  return listFiles(target);
}

/** Remove a partially created assignment directory, used to undo a failed pass. */
export async function removeAssignment(workspace: string, id: string): Promise<void> {
  await rm(path.join(workspace, id), { recursive: true, force: true });
}

// ---------------------------------------------------------------------------
// resolving "which assignment am I grading?"
// ---------------------------------------------------------------------------

export interface Resolved {
  workspace: string;
  assignmentDir: string;
  id: string;
  state: WorkspaceState | null;
}

/**
 * Work out which assignment to grade, in order of precedence:
 *   1. `--id` / `--dir`, which are explicit;
 *   2. the basename of the working directory, when it names a real assignment;
 *   3. the workspace's recorded `current` assignment.
 *
 * The third case is what makes bare `grade` work from the workspace root.
 */
export async function resolveAssignment(opts: {
  workspace: string;
  cwd: string;
  id?: string;
  dir?: string;
}): Promise<Resolved> {
  const root = packageRoot();
  const cfgDir = path.join(root, "data", "configs");
  const ids = new Set(
    (await readdir(cfgDir)).filter((f) => f.endsWith(".json")).map((f) => f.slice(0, -5)),
  );

  const state = await readState(opts.workspace);
  const cwd = path.resolve(opts.cwd);

  if (opts.dir) {
    const assignmentDir = path.resolve(opts.dir);
    const id = opts.id ?? path.basename(assignmentDir);
    if (!ids.has(id)) throw new ConfigError(`unknown assignment "${id}"`);
    return { workspace: opts.workspace, assignmentDir, id, state };
  }

  // cwd is (inside) an assignment directory
  const base = path.basename(cwd);
  if (ids.has(base)) {
    const assignmentDir = existsSync(path.join(cwd, "grade.txt")) || true ? cwd : cwd;
    return { workspace: opts.workspace, assignmentDir, id: base, state };
  }
  // cwd is a subdirectory of one
  for (const id of ids) {
    if (isInside(cwd, path.join(opts.workspace, id))) {
      return { workspace: opts.workspace, assignmentDir: path.join(opts.workspace, id), id, state };
    }
  }

  if (opts.id) {
    if (!ids.has(opts.id)) throw new ConfigError(`unknown assignment "${opts.id}"`);
    return {
      workspace: opts.workspace,
      assignmentDir: path.join(opts.workspace, opts.id),
      id: opts.id,
      state,
    };
  }

  if (state?.current) {
    return {
      workspace: opts.workspace,
      assignmentDir: path.join(opts.workspace, state.current),
      id: state.current,
      state,
    };
  }

  throw new ConfigError(
    `could not tell which assignment to grade.\n` +
      `Run this from inside an assignment directory, or from a workspace created by \`grade init\`.`,
  );
}

/** Progress summary, for `grade status`. */
export async function progress(root: string, state: WorkspaceState | null) {
  const ids = (await listAssignmentIds(root)).sort(compareAssignmentIds);
  const done = new Set(state?.completed ?? []);
  return ids.map((id) => ({
    id,
    status: done.has(id) ? ("done" as const) : id === state?.current ? ("current" as const) : ("locked" as const),
  }));
}

/** Advance the workspace after a pass. Returns the newly unlocked assignment. */
export async function advance(
  root: string,
  workspace: string,
  id: string,
  state: WorkspaceState | null,
  next: string | null,
): Promise<{ unlocked: string | null; skipped: boolean }> {
  const completed = [...new Set([...(state?.completed ?? []), id])];
  let unlocked: string | null = null;
  let skipped = false;

  if (next) {
    try {
      const files = await scaffoldAssignment(root, workspace, next);
      if (files.length === 0) skipped = true; // already present
      else unlocked = next;
    } catch (err) {
      if (err instanceof WorkspaceError) throw err;
      throw err;
    }
    // Even when the directory already existed, the student is now on `next`.
  }

  await writeState(workspace, {
    version: STATE_VERSION,
    initialized: state?.initialized ?? new Date().toISOString(),
    current: next,
    completed,
    packageRoot: root,
  });

  return { unlocked, skipped };
}

/** Config id list, for help text. */
export async function knownAssignments(root: string): Promise<string[]> {
  return (await listAssignmentIds(root)).sort(compareAssignmentIds);
}

/** Read one config, tolerating a missing one (used by status/list). */
export async function describe(root: string, id: string): Promise<{ id: string; type: string } | null> {
  try {
    return { id, type: (await readConfig(root, id)).type };
  } catch {
    return null;
  }
}
