/*
 * drivers/08_testing/isprime_probe.c
 *
 * Reconstructed grader driver for 08_testing.
 *
 * WHAT THE ASSIGNMENT IS
 * ----------------------
 * 08_testing/README hands the student five *prebuilt* Linux programs --
 * `isPrime-correct` and `isPrime-broken1` .. `isPrime-broken4` -- and asks for
 * four answer files `input.1` .. `input.4`, where `input.N` holds the command
 * line argument that makes `isPrime-brokenN` disagree with `isPrime-correct`.
 * For example:
 *
 *     $ ./isPrime-correct 3
 *     3 is prime
 *     $ ./isPrime-correct 4
 *     4 is not prime
 *
 * The five programs are Linux x86-64 ELF executables and cannot be run (or
 * linked) on this machine, so the grader cannot shell out to them.  This file
 * instead contains all five programs, recovered instruction-by-instruction
 * from `re/elf/08_testing__isPrime-{correct,broken1,broken2,broken3,broken4}.md`
 * (generated by tools/re/elfdump.py).  It then plays the role of the original
 * 2024 harness: for each `input.N` it runs `isPrime-brokenN` and
 * `isPrime-correct` on the argument and reports whether they disagree.
 *
 * RECOVERED DETAILS (all addresses are from the ELF reports)
 * ---------------------------------------------------------
 *   * Every program parses argv[1] with
 *         strtol(argv[1], &end, 0)          (main+0x23: xorl %edx,%edx)
 *     rejects it when `end == argv[1] || *end != '\0'` and then prints with
 *         "%ld is prime\n" / "%ld is not prime\n"   (.rodata +0x70 / +0x7e)
 *     failing that with
 *         "Ooops, %s does not seem to be a number!\n"  (.rodata +0x40)
 *     and, when argc != 2,
 *         puts("Please provide exactly one number to test for primailty")
 *     followed by `return 1`.
 *   * correct: `if (n <= 1) return 0; if (n == 2) return 1;
 *     if (!(n & 1)) return 0; for (i = 2; i != n; i++) if (n % i == 0) return 0;`
 *     (isPrime+0x0 .. isPrime+0x36).
 *   * broken1: the `n <= 1` branch falls into a second test for `n == 1`
 *     (main+0x91 `jle 0x4005a1`, then 0x4005a1 `je 0x400586`), so 1 -- and only
 *     1 -- is reported prime.
 *   * broken2: the result is forced to "not prime" when `n > 100`
 *     (main+0x8b `cmpq $0x64,%rdi` / `jle`), after the usual trial division.
 *   * broken3: byte-for-byte the correct program except that an argument which
 *     does not parse as a number is reported as `"%s is not prime\n"`
 *     (.rodata +0x40 == 0x4007e0) instead of the "Ooops" message.
 *   * broken4: for a negative n the not-prime path is a non-terminating loop
 *     (main 0x4005c1 `jmp 0x4005c1`), i.e. the program hangs instead of
 *     printing "-7 is not prime".  `isPrime-broken4 -7` therefore never exits.
 *
 * VALIDATION
 * ----------
 * The four answer files this repository's student submitted are
 *   input.1 = 1      input.2 = 101      input.3 = 7.0      input.4 = -7
 * and each one is exactly the minimal case for the recovered bug above
 * (1 -> broken1, 101 -> the first prime > 100 -> broken2, 7.0 -> the unparsable
 * argument -> broken3, -7 -> the hung negative case -> broken4).  Running this
 * driver against them reproduces the original `grade.txt`, where all four
 * cases passed.
 *
 * USAGE
 * -----
 *   isprime_probe <N> <answer-file>   run case N (1..4), print the verdict
 *   isprime_probe --run <program> [arg]   act as one of the five programs
 *
 * Exit status 0 means "this input shows isPrime-brokenN is broken".
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>

#define MAX_OUT 512
#define MAX_TOK 8
#define MAX_ARG 512
/* The original harness compared the outputs of two short-lived programs; a
 * program that does not finish inside this window is treated as producing no
 * output at all, which is what makes `isPrime-broken4 -7` detectable.  It is
 * deliberately generous: a student may legitimately answer brokens1/2/3 with a
 * large number, and the two trial-division loops then really do run. */
#define CASE_TIMEOUT_SECONDS 5

/* ------------------------------------------------------------------ *
 * The five programs, recovered from the ELF reports.                  *
 * ------------------------------------------------------------------ */

static int isPrime_correct(long n) {
  if (n <= 1) return 0;
  if (n == 2) return 1;
  if ((n & 1) == 0) return 0;
  for (long i = 2; i != n; i++) {
    if (n % i == 0) return 0;
  }
  return 1;
}

/* isPrime-broken1: `if (n <= 1)` is compiled as a test for `n == 1` that
 * answers "prime", so 1 is claimed to be prime. */
static int isPrime_broken1(long n) {
  if (n <= 1) return n == 1;
  return isPrime_correct(n);
}

/* isPrime-broken2: everything above 100 is called "not prime", after the
 * same trial division the correct program performs. */
static int isPrime_broken2(long n) {
  int prime = isPrime_correct(n); /* the loop really is executed first */
  if (n > 100) return 0;
  return prime;
}

/* isPrime-broken3 has the same primality logic as the correct program; only
 * its "that is not a number" message differs, which is modelled by main(). */

/* isPrime-broken4: a negative argument reaches the not-prime path, which the
 * recovered program never leaves (4005c1: jmp 4005c1). */
static int isPrime_broken4(long n) {
  if (n <= 1) {
    if (n < 0) {
      volatile unsigned long spin = 0;
      for (;;) spin++; /* exactly what the binary does: it never returns */
    }
    return 0;
  }
  return isPrime_correct(n);
}

static int isPrime_for(const char *program, long n) {
  if (strcmp(program, "broken1") == 0) return isPrime_broken1(n);
  if (strcmp(program, "broken2") == 0) return isPrime_broken2(n);
  if (strcmp(program, "broken4") == 0) return isPrime_broken4(n);
  return isPrime_correct(n);
}

/* argv holds the program's own argv[1..]; argv[0] is the program name. */
static int program_main(const char *program, int argc, char **argv) {
  if (argc != 2) {
    puts("Please provide exactly one number to test for primailty");
    return 1;
  }
  char *end = NULL;
  long n = strtol(argv[1], &end, 0);
  if (end == argv[1] || end == NULL || *end != '\0') {
    if (strcmp(program, "broken3") == 0) {
      printf("%s is not prime\n", argv[1]);
    } else {
      printf("Ooops, %s does not seem to be a number!\n", argv[1]);
    }
    return 1;
  }
  if (isPrime_for(program, n)) {
    printf("%ld is prime\n", n);
  } else {
    printf("%ld is not prime\n", n);
  }
  return 0;
}

/* ------------------------------------------------------------------ *
 * Running one program as a child, with the same timeout discipline    *
 * the original harness must have used to see the hung broken4.        *
 * ------------------------------------------------------------------ */

struct run {
  char out[MAX_OUT];
  size_t len;
  int status;    /* exit status, or -1 when killed by a signal */
  int signalled; /* 1 when it did not exit on its own */
};

static int run_program(const char *self, const char *program, char **tokens,
                       int ntokens, struct run *r) {
  int fds[2];
  r->len = 0;
  r->status = -1;
  r->signalled = 0;
  r->out[0] = '\0';

  if (pipe(fds) != 0) return -1;
  pid_t pid = fork();
  if (pid < 0) {
    close(fds[0]);
    close(fds[1]);
    return -1;
  }
  if (pid == 0) {
    if (dup2(fds[1], STDOUT_FILENO) < 0) _exit(127);
    close(fds[0]);
    close(fds[1]);
    alarm(CASE_TIMEOUT_SECONDS);
    char *argv[MAX_TOK + 4];
    int n = 0;
    argv[n++] = (char *)self;
    argv[n++] = (char *)"--run";
    argv[n++] = (char *)program;
    for (int i = 0; i < ntokens; i++) argv[n++] = tokens[i];
    argv[n] = NULL;
    execv(self, argv);
    _exit(127);
  }

  close(fds[1]);
  size_t total = 0;
  for (;;) {
    ssize_t k = read(fds[0], r->out + total, sizeof(r->out) - 1 - total);
    if (k <= 0) break;
    total += (size_t)k;
    if (total >= sizeof(r->out) - 1) break;
  }
  r->out[total] = '\0';
  r->len = total;
  close(fds[0]);

  int st = 0;
  if (waitpid(pid, &st, 0) < 0) return -1;
  r->signalled = WIFSIGNALED(st) ? 1 : 0;
  r->status = WIFEXITED(st) ? WEXITSTATUS(st) : -1;
  return 0;
}

static int runs_agree(const struct run *a, const struct run *b) {
  if (a->status != b->status) return 0;
  if (a->signalled != b->signalled) return 0;
  if (a->len != b->len) return 0;
  return memcmp(a->out, b->out, a->len) == 0;
}

/* ------------------------------------------------------------------ *
 * The case itself                                                     *
 * ------------------------------------------------------------------ */

/* `$(cat input.N)` in the original shell harness: split the file on IFS
 * whitespace, which is why a multi-word answer file ends up as several
 * arguments and trips the "exactly one number" message. */
static int split_tokens(char *text, char *tokens[], int max) {
  int n = 0;
  char *p = text;
  while (*p != '\0' && n < max) {
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    if (*p == '\0') break;
    tokens[n++] = p;
    while (*p != '\0' && *p != ' ' && *p != '\t' && *p != '\n' && *p != '\r') p++;
    if (*p != '\0') *p++ = '\0';
  }
  return n;
}

static void describe(const char *label, const struct run *r) {
  if (r->signalled) {
    printf("%s: did not terminate within %d seconds\n", label, CASE_TIMEOUT_SECONDS);
  } else if (r->len == 0) {
    printf("%s: (no output, exit status %d)\n", label, r->status);
  } else {
    printf("%s: %s", label, r->out);
  }
}

int main(int argc, char **argv) {
  if (argc >= 2 && strcmp(argv[1], "--run") == 0) {
    if (argc < 3) {
      fprintf(stderr, "usage: %s --run <program> [args...]\n", argv[0]);
      return 2;
    }
    return program_main(argv[2], argc - 2, argv + 2);
  }

  if (argc != 3) {
    fprintf(stderr, "usage: %s <1|2|3|4> <input-file>\n", argv[0]);
    return 2;
  }
  int index = atoi(argv[1]);
  if (index < 1 || index > 4) {
    fprintf(stderr, "case index must be 1, 2, 3 or 4 (got %s)\n", argv[1]);
    return 2;
  }
  char broken[16];
  snprintf(broken, sizeof(broken), "broken%d", index);

  char text[MAX_ARG];
  FILE *f = fopen(argv[2], "r");
  if (f == NULL) {
    printf("your answer file %s was not found\n", argv[2]);
    fprintf(stderr, "cannot open %s\n", argv[2]);
    return 1;
  }
  size_t got = fread(text, 1, sizeof(text) - 1, f);
  fclose(f);
  text[got] = '\0';

  char *tokens[MAX_TOK];
  int ntokens = split_tokens(text, tokens, MAX_TOK);

  struct run correct, subject;
  if (run_program(argv[0], "correct", tokens, ntokens, &correct) != 0 ||
      run_program(argv[0], broken, tokens, ntokens, &subject) != 0) {
    printf("could not run the reconstructed isPrime programs\n");
    return 1;
  }

  if (!runs_agree(&correct, &subject)) {
    printf("Your file matched the expected output\n");
    return 0;
  }

  printf("input.%d does not show that isPrime-%s is broken\n", index, broken);
  describe("isPrime-correct", &correct);
  describe(broken, &subject);
  return 1;
}
